version: "3.1"
services:
  priorizador:
    build:
      context: .
      dockerfile: Dockerfile
    image: priorizador
    command: make init
    environment:
      TOKEN: $TOKEN
    volumes:
      - $PWD:/workdir