version: "3.1"
services:
  prioritizator:
    build:
      context: .
      dockerfile: Dockerfile
    image: islasgeci/prioritizator:latest
    command: make init
    environment:
      TOKEN: $TOKEN
    volumes:
      - $PWD:/workdir
